import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

test("Pages publishes a branchable Beat Fish trainer with action ranges and hand-history estimation", async () => {
  const solverIndex = await readFile(new URL("../dist/site/index.html", import.meta.url), "utf8");
  const trainer = await readFile(new URL("../dist/site/trainer.html", import.meta.url), "utf8");
  const trainerJs = await readFile(new URL("../dist/site/trainer.js", import.meta.url), "utf8");
  const trainerCss = await readFile(new URL("../dist/site/styles/trainer.css", import.meta.url), "utf8");
  const fishModel = await readFile(new URL("../dist/src/fish-model.js", import.meta.url), "utf8");
  const heroExploit = await readFile(new URL("../dist/src/hero-exploit.js", import.meta.url), "utf8");
  const multiwayPractice = await readFile(new URL("../dist/src/multiway-practice.js", import.meta.url), "utf8");

  assert.match(solverIndex, /href="trainer\.html"/);
  assert.match(trainer, /<title>Beat Fish · Poker Solver<\/title>/);
  assert.match(trainer, /id="reveal-range"/);
  assert.match(trainer, /id="history-back"/);
  assert.match(trainer, /id="history-forward"/);
  assert.match(trainer, /id="branch-trail"/);
  assert.match(trainer, /id="range-grid"/);
  assert.match(trainer, /id="range-color-legend"/);
  assert.match(trainer, /id="response-sizing-options"/);
  assert.match(trainer, /id="response-action-options"/);
  assert.match(trainer, /id="opponent-seats"/);
  assert.match(trainer, /id="range-opponent-options"/);
  assert.match(trainer, /id="range-combo-detail-list"/);
  assert.match(trainer, /id="mode-analyze"/);
  assert.match(trainer, /id="history-input"/);
  assert.match(trainer, /id="analyze-history"/);
  assert.match(trainer, /id="history-range-grid"/);
  assert.match(trainer, /id="history-street-tabs"/);
  assert.match(trainer, /id="history-street-context"/);
  assert.match(trainer, /role="tablist" aria-label="Estimated range by street"/);
  assert.match(trainer, /Street tabs let you rewind the same binary range/);
  assert.match(trainer, /Colors show the modeled fish action—fold, call, or raise/);
  assert.match(trainer, /Play 6-handed practice/);
  assert.match(trainer, /Estimate heads-up history/);
  assert.match(trainer, /Heads-up only: it does not model extra players/);
  assert.match(trainer, /not a claimed exact multiway solve/);
  assert.match(trainer, /value requires worse calls and bluffs require better folds/);
  assert.match(trainer, /Opponent ranges never use solver charts/);
  assert.match(trainer, /TT\/99 still never 4-bet/);
  assert.match(trainer, /KJs, QJs, and JTs get one extra call against a small reraise/);
  assert.match(trainer, /missed big aces peel only small postflop bets/);
  assert.match(trainer, /Medium showdown value checks instead of becoming a paired-board bluff/);
  assert.match(trainer, /position, sizing, dead money, and what that player did earlier/);
  assert.match(trainer, /every exact combo is played from the fish's perspective/);
  assert.match(trainer, /heads-up donks and checked-to stabs can contain air or strong draws/);
  assert.match(trainer, /multiway donks, turn raises after prior aggression, and passive river stabs stay strongly value-weighted/);
  assert.match(trainer, /value, semi-bluff, or bluff/);
  assert.match(trainer, /150bb/);
  assert.match(trainer, /\$450/);
  assert.match(trainer, /fold,\s+limp, open-raise, call, or 3-bet/);
  assert.doesNotMatch(trainer, /more likely|posterior/i);

  assert.match(trainerJs, /observeFishAction/);
  assert.match(trainerJs, /partitionFishRange/);
  assert.match(trainerJs, /createTrainerTree/);
  assert.match(trainerJs, /trainerTreeChild/);
  assert.match(trainerJs, /preflopLookupStrategyForClass/);
  assert.match(trainerJs, /createSixHandedPracticeScenario/);
  assert.match(trainerJs, /estimateHeroMultiwayEquity/);
  assert.match(trainerJs, /preflop-facing-open/);
  assert.match(trainerJs, /preflop-facing-threebet/);
  assert.match(trainerJs, /opponentsRespondToThreeBet/);
  assert.match(trainerJs, /opponentsRespondToFourBet/);
  assert.match(trainerJs, /postflop-vs-fish-bet/);
  assert.match(trainerJs, /buildVsFishBetDecision/);
  assert.match(trainerJs, /shouldDefaultToObserved/);
  assert.match(trainerJs, /choiceId: button\.dataset\.responseChoice \|\| "current"/);
  assert.match(trainerJs, /dealPracticeRunout/);
  assert.doesNotMatch(trainerJs, /dealCheckThroughRunout/);
  assert.match(trainerJs, /analyzeFishHandHistory/);
  assert.match(trainerJs, /renderHistoryStreetTabs/);
  assert.match(trainerJs, /streetSnapshots/);
  assert.match(trainerJs, /lastFishContext/);
  assert.match(trainerJs, /rangeCellGradient/);
  assert.match(trainerJs, /fishDecisionForCombo/);
  assert.match(trainerJs, /Fish sees:/);
  assert.match(trainerJs, /Explore this branch/);
  assert.match(trainerJs, /View saved branch/);
  assert.match(trainerJs, /choiceReasons/);
  assert.match(trainerJs, /recommendHeroPostflopPlan/);
  assert.doesNotMatch(trainerJs, /Thin value \/ cheap pressure/);
  assert.match(trainerJs, /What is wrong with this choice/);
  assert.match(trainerJs, /stack: 150/);
  assert.doesNotMatch(trainerJs, /reweighted by how often|posterior range/i);

  assert.match(heroExploit, /Betting purpose \+ exact response ranges/);
  assert.match(heroExploit, /Value requires worse calls; a bluff requires better folds/);

  assert.match(trainerCss, /--range-fold/);
  assert.match(trainerCss, /--range-call/);
  assert.match(trainerCss, /--range-raise/);
  assert.match(trainerCss, /\.analyzer-panel/);
  assert.match(trainerCss, /\.history-street-tabs/);
  assert.match(trainerCss, /\.history-street-tab\[aria-selected="true"\]/);
  assert.match(trainerCss, /\.fish-range-cell\.excluded/);
  assert.match(trainerCss, /\.branch-trail/);
  assert.match(trainerCss, /\.response-explorer/);
  assert.match(trainerCss, /\.exact-combo-list/);
  assert.match(trainerCss, /\.exact-combo-thought/);
  assert.match(trainerCss, /\.opponent-seats/);
  assert.match(trainerCss, /\.opponent-range-picker/);

  assert.match(fishModel, /Deterministic novice action rule/);
  assert.match(fishModel, /fishActionForCombo/);
  assert.match(fishModel, /fishDecisionForCombo/);
  assert.match(fishModel, /fishPerceptionForCombo/);
  assert.match(fishModel, /partitionFishRange/);
  assert.match(fishModel, /fishRangeContinuingVsOpenSizes/);
  assert.doesNotMatch(fishModel, /fishActionProbabilities/);
  assert.doesNotMatch(fishModel, /\.probability/);
  assert.doesNotMatch(fishModel, /preflopLookupStrategyForClass/);
  assert.match(fishModel, /Never turns TT or 99 into a 4-bet/);
  assert.match(fishModel, /isNarrowRiverBlockerBluff/);
  assert.match(fishModel, /isHeadsUpDonkBluff/);
  assert.match(fishModel, /turn raises after prior aggression stay almost pure value/);

  assert.match(multiwayPractice, /SIX_HANDED_OPPONENTS/);
  assert.match(multiwayPractice, /limperCount/);
  assert.match(multiwayPractice, /raisedPlan/);
  assert.match(multiwayPractice, /threeBetPlan/);
  assert.match(multiwayPractice, /takesEveryAction/);
});
